backend:
  name: github
  repo: VermontDepartmentOfHealth/docs # Path to your GitHub repository
  branch: master # Branch to update (optional; defaults to master)

media_folder: "assets/images/uploads" # Media files will be stored in the repo under images/uploads

collections:
  - name: "posts" # Used in routes, e.g., /admin/collections/posts
    label: "Posts" # Used in the UI
    folder: "posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Summary", name: "summary", widget: "string"}
      - {label: "Tags", name: "tags", widget: "select", multiple: true, default: ["post"], options: ["post", "draft", "how-to", "overview", "process", "redgate", "sql", "workforce"]}
      - {label: "Authors", name: "authors", widget: "select", multiple: true, options: ["Brian", "John", "Kyle", "Sandra"]}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Update Date", name: "updated", widget: "date"}
      - {label: "Body", name: "body", widget: "markdown"}
